# Generated by Django 5.0.7 on 2025-11-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsource',
            name='has_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='In Progress', max_length=100),
        ),
    ]
