# Generated by Django 5.2.6 on 2025-11-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_leadsource_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        ),
    ]
