# Generated by Django 5.2.7 on 2025-11-08 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_boq_boqitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boqs', to='lms.project'),
        ),
        migrations.CreateModel(
            name='InventoryOrderRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.IntegerField()),
                ('available_quantity', models.IntegerField()),
                ('shortage_quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_requirements', to='lms.boq')),
                ('boq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requirement', to='lms.boqitem')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requirements', to='lms.inventoryitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_requirements', to='lms.project')),
            ],
            options={
                'verbose_name': 'Inventory Order Requirement',
                'verbose_name_plural': 'Inventory Order Requirements',
                'ordering': ['-created_at'],
            },
        ),
    ]
