# Generated by Django 5.2.6 on 2025-11-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_boq_project_inventoryorderrequirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsource',
            name='status',
        ),
    ]
