# Generated by Django 5.2.6 on 2025-11-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_remove_leadsource_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsource',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('contacted', 'Contacted'), ('boq', 'BOQ'), ('advanced', 'Advanced'), ('won', 'Won'), ('closed', 'Closed'), ('lost', 'Lost')], default='open', max_length=20),
        ),
    ]
