# Generated by Django 5.2.6 on 2025-11-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_leadsource_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsource',
            name='status',
        ),
    ]
