# Generated by Django 5.2.6 on 2025-11-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_task_assigned_by_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsource',
            name='city',
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
